errors = {
    # Baseado na documentação oferecida pelo Gerente de Telecomunicações do Grupo Mateus, Arthur Turrini
    '00': ('Transação Nacional Autorizada com Sucesso.', 'Sem ação.', False),
    '0': ('Transação Nacional Autorizada com Sucesso.', 'Sem ação.', False),
    '01': ('Transção referida pelo emissor.', 'Oriente o cliente a contatar o emissor do cartão.', False),
    '1': ('Transção referida pelo emissor.', 'Oriente o cliente a contatar o emissor do cartão.', False),
    '02': ('Transção referida pelo emissor.', 'Oriente o cliente a contatar o emissor do cartão.', False),
    '2': ('Transção referida pelo emissor.', 'Oriente o cliente a contatar o emissor do cartão.', False),
    '03': ('Não foi encontrada a transação.\nEste erro pode ser:\n- Número de parcelas ultrapassa o permitido.\n- Código de segurança inválido.\n- Número de cartão inválido.\n- Instabilidade no sistema da adquirente ( a loja ).', 'Sem ação.', True),
    '3': ('Não foi encontrada a transação.\nEste erro pode ser:\n- Número de parcelas ultrapassa o permitido.\n- Código de segurança inválido.\n- Número de cartão inválido.\n- Instabilidade no sistema da adquirente ( a loja ).', 'Sem ação.', True),
    '04': ('Cartão com restrição.', 'Oriente o cliente a contatar o emissor do cartão (Problemas com o cartão).', False),
    '4': ('Cartão com restrição.', 'Oriente o cliente a contatar o emissor do cartão (Problemas com o cartão).', False),
    '05': ('Transação não autorizada.', 'Oriente o cliente a contatar o emissor do cartão (Não autorizada pelo emissor do cartão).', False),
    '5': ('Transação não autorizada.', 'Oriente o cliente a contatar o emissor do cartão (Não autorizada pelo emissor do cartão).', False),
    '06': ('Tente novamente. Problemas ocorridos na transação eletrônica, instabilidade da adquirente ( a loja )', 'Sem ação.', True),
    '6': ('Tente novamente. Problemas ocorridos na transação eletrônica, instabilidade da adquirente ( a loja )', 'Sem ação.', True),
    '07': ('Cartão com restrição.', 'Oriente o cliente a contatar o emissor do cartão (Problemas com o cartão).', False),
    '7': ('Cartão com restrição.', 'Oriente o cliente a contatar o emissor do cartão (Problemas com o cartão).', False),
    '08': ('Código de segurança inválido. O código de segurança foi informado errado no momento da compra.', 'Sem ação.', False),
    '8': ('Código de segurança inválido. O código de segurança foi informado errado no momento da compra.', 'Sem ação.', False),
    '10': ('Não é permitido o envio do cartão. Adquirente ( a loja ) está com os serviços instáveis.', 'Caso o erro continue entre em contato com nosso suporte técnico.', False),
    '11': ('Transação Internacional Autorizada com sucesso.', 'Sem ação.', False),
    '12': ('Transação inválida. Venda não autorizada pelo banco emissor do cartão. Cartão informado no momento da compra está incorreto.', 'Sem ação.', False),
    '13': ('Valor inválido.', 'Verifique valor mínimo de R$5,00 para parcelamento.', False),
    '14': ('Cartão inválido.', 'Sem ação.', False),
    '15': ('Emissor inválido. Emissor sem comunicação', 'Sem ação.', True),
    '19': ('Não foi possível processar a transação.', 'Indique refazer a transação ou tentar novamente mais tarde.', True),
    '21': ('Cancelamento não efetuado. Não foi possível processar o cancelamento.', 'Sem ação.', False),
    '22': ('Parcelamento inválido. Não foi possível processar a transação, número de parcelas inválidas o valor inválido.', 'Indique refazer a transação confirmando os dados informados.', True),
    '24': ('Quantidade de parcelas inválido. Não foi possível processar a transação. Quantidade de parcelas inválido.', 'Sem ação.', False),
    '30': ('Não foi possível processar a transação.', 'Solicite ao cliente que reveja os dados e tente novamente. Se o erro persistir, o cliente deve entre em contato com banco emissor.', False),
    '39': ('Transação não autorizada. Erro no banco emissor do cartão.', 'Indique entrar em contato com banco emissor.', False),
    '41': ('Cartão com restrição.', 'Oriente o cliente a contatar o emissor do cartão (Problemas com o cartão).', False),
    '43': ('Cartão com restrição.', 'Oriente o cliente a contatar o emissor do cartão (Problemas com o cartão).', False),
    '51': ('Saldo insuficiente', 'Cliente deve entrar em contato com o banco emissor.', True),
    '52': ('Cartão com dígito de controle inválido. Não foi possível processar a transação. Cartão com dígito de controle inválido.', 'Sem ação', False),
    '54': ('Cartão vencido', 'Caso os dados informados estejam corretos, cliente deve entrar em contato com o banco para verificar se cartão ainda é válido.', False),
    '55': ('Senha inválida. Senha informada está errada.', 'Sem ação', False),
    '57': ('Transação não permitida ou não autorizada. Venda não autorizada pelo emissor do cartão, pois o cartão utilizado não faz parte da rede Verified by Visa ou o sistema de prevenção do banco não autorizou a compra.', 'Neste caso o cliente deverá realizar contato com o banco emissor do cartão e informar que está tentando realizar uma compra no valor R$XXX e não está sendo autorizada.', False),
    '58': ('Transaçãonão permitida', 'Sem ação.', False),
    '60': ('Transação não autorizada', 'Oriente o cliente a contatar o emissor do cartão.', False),
    '61': ('Banco emissor Visa indisponível. Transação não autorizada.', 'Tente novamente. Se o erro persistir, solicite entrar em contato com o banco emissor.', True),
    '62': ('Cartão com restrição. Cartão com algum bloqueio para transações online.', 'Oriente o cliente a contatar o emissor do cartão. ', False),
    '63': ('Cartão com restrição. Possível erro de segurança ao tentar processar.', 'Oriente o cliente a contatar o emissor do cartão.', False),
    '65': ('Cartão com restrição. Transação negada.', 'Oriente o cliente a contatar o emissor do cartão (Problemas com o cartão).', False),
    '67': ('Transação não autorizada. Cartão bloqueado para compras no dia. Bloqueio pode ter ocorrido por excesso de tentativas inválidas.', 'Sem ação', True),
    '70': ('Transação não autorizada. Limite excedido / Sem saldo.', 'Oriente a entrar em contato com o banco emissor.', True),
    '74': ('Transação não autorizada. A senha está vencida', 'Sem ação.', False),
    '75': ('Cartão com restrição. Motivo provável, bloqueio de senha.', 'Oriente o cliente a contatar o emissor do cartão.', False),
    '76': ('Tente novamente', 'Sem ação.', True),
    '77': ('Cancelamento não efetuado. Não foi localizado a transação original.', 'Sem ação.', False),
    '78': ('Cartão não foi desbloqueado pelo cliente', 'Oriente o cliente a desbloqueá-lo junto ao emissor do cartão.', False),
    '80': ('Transação não autorizada. Data da transação ou data do primeiro pagamento inválida.', 'Refazer confirmando dados.', False),
    '81': ('Transação negada', 'Sem ação.', False),
    '82': ('Transação inválida. Provável código de segurança incorreto ou inválido.', 'Sem ação.', False),
    '85': ('Transação não permitida. Falha da operação, houve um erro no processamento. ', 'Solicite ao cliente que digite novamente os dados do cartão.', False),
    '88': ('Erro na transação. Transação não autorizada, erro na transação. ', 'O cliente deve tentar novamente e se o erro persistir, entrar em contato com o banco emissor.', True),
    '90': ('Transação não permitida. Falha da operação.', 'Solicite ao cliente que digite novamente os dados do cartão.', False),
    '91': ('Banco indisponível. Emissor do cartão sem comunicação.', 'Oriente cliente a aguardar alguns minutos e tente novamente.', True),
    '92': ('Transação não autorizada. Tempo de comunicação excedido.', 'Sem ação.', False),
    '94': ('Transação não autorizada. Transação desfeita pela bandeira (Visa ou Mastercard).', 'Sem ação.', False),
    '96': ('Tente novamente. Provável venda abaixo de R$ 1,00. Falha no envio da autorização.', 'Sem ação.', True),
    '99': ('Sistema do banco temporariamente fora de operação.', 'Oriente tentar novamente mais tarde.', False),
    'AA': ('Tempo Excedido. Tempo excedido na comunicação com o banco emissor. ', 'Oriente o cliente a tentar novamente, se o erro persistir será necessário que o cliente contate seu banco emissor.', True),
    'AC': ('Cartão de débito sendo usado como crédito.', 'O cliente deve usar um cartão de crédito.', False),
    'AE': ('Tente mais tarde. Tempo excedido na comunicação com o banco emissor.', 'Oriente o cliente a tentar novamente.', True),
    'AF': ('Transação não permitida. Falha da operação. Houve um erro no processamento. ', 'Solicite ao cliente que digite novamente os dados do cartão.', False),
    'AG': ('Transação não permitida. Falha da operação. Houve um erro no processamento. ', 'Solicite ao cliente que digite novamente os dados do cartão.', False),
    'AI': ('Transação não autorizada. Autenticação não foi realizada. Autenticação não foi realizada. O cliente não concluiu a autenticação.', 'Sem ação.', False),
    'AV': ('Transação não autorizada. Dados inválidos. Falha na validação dos dados da transação.', 'Oriente o cliente a rever os dados e tentar novamente.', True),
    'BD': ('Transação não permitida. Falha da operação. Houveum erro no processamento.', 'Solicite ao cliente que digite novemante os dados do cartão.', False),
    'BL': ('Transação não autorizada. Limite diário excedido.', 'Solicite ao cliente que entre em contato com seu banco emissor.', False),
    'BM': ('Transação não autorizada. Cartão inválido. Pode ser bloqueio do cartão no banco emissor.', 'Sem ação.', False),
    'BN': ('Transação não autorizada. Cartão ou conta bloqueado. O cartão ou a conta do cliente está bloqueada.', 'Solicite ao cliente que entre em contato com seu banco emissor.', False),
    'BV': ('Transação não autorizada. Cartão vencido.', 'Sem ação.', False),
    'CF': ('Transação não autorizada. Falha na validação dos dados.', 'Solicite ao cliente que entre em contato com o banco emissor.', False),
    'EE': ('Transação não permitida. Valor da parcela inferior ao mínimo permitido. Não é permitido parcelas inferiores a R$ 5,00.', 'Necessário rever calculo para parcelas.', False),
    'FA': ('Transação não autorizada.', 'Sem ação.', False),
    'FC': ('Transação não autorizada. Ligue emissor', 'Oriente o cliente a entrar em contato com o banco emissor.', False),
    'GA': ('Transação não autorizada. Referida pela Cielo.', 'Oriente o cliente a aguardar alguns instantes e tentar novamente', True),
    'GD': ('Transação não permitida.', 'Transação não é possível ser processada no estabelecimento.Entre em contato com a administradora do cartão para obter mais detalhes.', True),
    'KA': ('Transação não permitida. Houve uma falha na validação dos dados.', 'Solicite ao cliente que reveja os dados e tente novamente.', True),
    'KE': ('Transação não autorizada. Falha na validação dos dados.', 'Sem ação.', False),
    'N7': ('Transação não autorizada. Código de segurança inválido.', 'Oriente o cliente corrigir os dados e tentar novamente.', True),
    'TEF': ('Solicitar Assinatura.', 'Operador deve pressionar 0 e Enter.', False),
    'DAI': ('Data abertura invalida. PDV com fechamento parcial.', 'Oriente um a **Fiscal de Loja** fazer o procedimento de fechamento para logo dar entrada ao operador.', True),
}