errors = {
    # Baseado na documentação oferecida pelo Gerente de Telecomunicações do Grupo Mateus, Arthur Turrini
    '00': ('Transação Nacional Autorizada com Sucesso', 'N/A', False),
    '01': ('Transção referida pelo emissor.', 'Oriente o portador a contatar o emissor do cartão.', False),
    '02': ('Transção referida pelo emissor.', 'Oriente o portador a contatar o emissor do cartão.', False),
    '03': ('Não foi encontrada a transação.\nEste erro pode ser:\n- Número de parcelas ultrapassa o permitido.\n- Código de segurança inválido.\n- Número de cartão inválido.\n- Instabilidade no sistema da adquirente.', 'N/A', True),
    '04': ('Cartão com restrição.', 'Oriente o portador a contatar o emissor do cartão (Problemas como cartão).', False),
    '05': ('Transação não autorizada.', 'Oriente o portador a contatar o emissor do cartão (Não autorizada pelo emissor).', False),
    '06': ('Tente novamente.', 'Problemas ocorridos na transação eletrônica, instabilidade da adquirente.', True),
    '07': ('Cartão com restrição.', 'Oriente o portador a contatar o emissor do cartão (Problemas com o cartão).', False),
    '08': ('Código de segurança inválido.', 'O código de segurança foi informado errado no momento da compra.', False),
    '10': ('Não é permitido o envio do cartão.', 'Adquirente está com os serviços instáveis, caso o erro continue ocorrendo entre em contato com nosso suporte técnico.', False),
    '11': ('Transação Internacional Autorizada com sucesso.', 'N/A.', False),
    '12': ('Transação inválida.', 'Venda não autorizada pelo banco emissor do cartão. Cartão informado no momento da compra está incorreto.', False),
    '13': ('Valor inválido.', 'Verifique valor mínimo de R$5,00 para parcelamento.', False),
    '14': ('Cartão inválido', 'N/A.', False),
    '15': ('Emissor inválido', 'Emissor sem comunicação.', True),
    '19': ('Refaça a transação ou tente novamente mais tarde.', 'Não foi possível processar a transação. Refaça a transação ou tente novamente mais tarde.', True),
    '21': ('Cancelamento não efetuado', 'Não foi possível processar o cancelamento.', False),
    '22': ('Parcelamento inválido. Número de parcelas inválidas', 'Não foi possível processar a transação. Valor inválido. Refazer a transação confirmando os dados informados.', False),
    '24': ('Quantidade de parcelas inválido.', 'Não foi possível processar a transação. Quantidade de parcelas inválido.', False),
    '30': ('Não foi possível processar a transação. Solicite ao portador que reveja os dados e tente novamente.', 'Não foi possível processar a transação. Solicite ao portador que reveja os dados e tente novamente. Se o erro persistir, entre em contato com a loja virtual.', False),
    '39': ('Transação não autorizada. Erro nobanco emissor.', 'Transação não autorizada. Entre em contato com seu banco emissor.', False),
    '41': ('Cartão com restrição.', 'Oriente o portador a contatar o emissor do cartão (Problemas com o cartão).', False),
    '43': ('Cartão com restrição.', 'Oriente o portador a contatar o emissor do cartão (Problemas com o cartão).', False),
    '51': ('Saldo insuficiente', 'Cliente deve entrar em contato com o banco.', True),
    '52': ('Cartão com dígito de controle inválido', 'Não foi possível processar a transação. Cartão com dígito de controle inválido.', False),
    '54': ('Cartão vencido', 'Caso os dados informados estejam corretos, cliente deve entrar em contato com o banco para verificar se cartão ainda é válido.', False),
    '55': ('Senha inválida.', 'Senha informada está errada.', False),
    '57': ('Transação não permitida ou não autorizada', 'Venda não autorizada pelo emissor do cartão, pois o cartão utilizado não faz parte da rede Verified by Visa ou o sistema de prevenção do banco não autorizou a compra, neste caso o cliente deverá realizar contato com banco emissor do cartão e informar que está tentando realizar uma compra no valor R$XXX e não está sendo autorizada.', False),
    '58': ('Transaçãonão permitida', 'N/A', False),
    '60': ('Transação não autorizada', 'Oriente o portador a contatar o emissor do cartão.', False),
    '61': ('Banco emissor Visa indisponível', 'Transação não autorizada. Tente novamente. Se o erro persistir, entre em contato com seu banco emissor.', True),
    '62': ('Cartão com restrição', 'Oriente o portador a contatar o emissor do cartão. Cartão com algum bloqueio para transações online.', False),
    '63': ('Cartão com restrição', 'Oriente o portador a contatar o emissor do cartão. Possível erro de segurança ao tentar processar.', False),
    '65': ('Cartão com restrição', 'Transação negada. oriente o portador a contatar o emissor do cartão (Problemas com o cartão).', False),
    '67': ('Transação não autorizada', 'Transação não autorizada. Cartão bloqueado para compras hoje. Bloqueio pode ter ocorrido por excesso de tentativas inválidas.', True),
    '70': ('Transação não autorizada. Limite excedido / Sem saldo.', 'Transação não autorizada. Entre em contato com seu banco emissor.', True),
    '74': ('Transação não autorizada.', 'Transação não autorizada. A senha está vencida', False),
    '75': ('Cartão com restrição', 'Motivo provável, bloqueio de senha. Oriente o portador a contatar o emissor do cartão.', False),
    '76': ('Tente novamente', 'N/A', True),
    '77': ('Cancelamento não efetuado', 'Cancelamento não efectuado. Não foi localizado a transação original.', False),
    '78': ('Cartão não foi desbloqueado pelo portador', 'Cartão bloqueado. Oriente o portador a desbloqueá-lo junto ao emissor do cartão.', False),
    '80': ('Transação não autorizada', 'Transação não autorizada. Data da transação ou data do primeiro pagamento inválida. Refazer confirmando dados.', False),
    '81': ('Transação negada', 'N/A', False),
    '82': ('Transação inválida', 'Provável código de segurança incorreto ou inválido.', False),
    '85': ('Transação não permitida. Falha da operação.', 'Transação não permitida. Houve um erro no processamento. Solicite ao portador que digite novamente os dados do cartão.', False),
    '88': ('Erro na transação', 'Transação não autorizada. Erro na transação. O portador deve tentar novamente e se o erro persistir, entrar em contato com o banco emissor.', True),
    '90': ('Transação não permitida. Falha da operação.', 'Transação não permitida. Houve um erro no processamento. Solicite ao portador que digite novamente os dados do cartão.', False),
    '91': ('Banco indisponível.', 'Emissor sem comunicação. Oriente cliente a aguardar alguns minutos e tente novamente.', True),
    '92': ('Transação não autorizada. Tempo de comunicação excedido.', 'Transação não autorizada. Tempo de comunicação excedido.', False),
    '94': ('Transação não autorizada', 'Transação desfeita pela bandeira.', False),
    '96': ('Tente novamente', 'Provável venda abaixo de R$ 1,00. Falha no envio da autorização.', True),
    '99': ('Sistema do banco temporariamente fora de operação.', 'Tente novamente mais tarde.', False),
    'AA': ('Tempo Excedido.', 'Tempo excedido na comunicação com o banco emissor. Oriente oportador a tentar novamente,se o erro persistir será necessário que o portador contate seu banco emissor.', True),
    'AC': ('Cartão de débito sendo usado como crédito.', 'Cartão de débito sendo usado como crédito. Portador deve usar um cartão de crédito.', False),
    'AE': ('Tente mais tarde.', 'Tempo excedido na comunicação com o banco emissor. Oriente o portador a tentar novamente.', True),
    'AF': ('Transação não permitida. Falha da operação.', 'Transação não permitida. Houve um erro no processamento. Solicite ao portador que digite novamente os dados do cartão.', False),
    'AG': ('Transação não permitida. Falha da operação.', 'Transação não permitida. Houve um erro no processamento. Solicite ao portador que digite novamente os dados do cartão.', False),
    'AI': ('Transação não autorizada. Autenticação não foi realizada', 'Transação não autorizada. autenticação não foi realizada. O portador não concluiu a autenticação.', False),
    'AV': ('Transação não autorizada. Dados inválidos.', 'Falha na validação dos dados da transação. Oriente o portador a rever os dados e tentar novamente.', True),
    'BD': ('Transação não permitida. Falha da operação.', 'Transação não permitida. Houveum erro noprocessamento. Solicite ao portador que digite novemante os dados do cartão.', False),
    'BL': ('Transação não autorizada. Limite diário excedido.', 'Transação não autorizada. Limite diário excedido. Solicite ao portador que entre em contato com seu banco emissor.', False),
    'BM': ('Transação não autorizada. Cartão inválido.', 'Transação não autorizada. Cartão inválido. Pode ser bloqueio do cartão no banco emissor.', False),
    'BN': ('Transação não autorizada. Cartão ou conta bloqueado.', 'Transação não autorizada. O cartão ou a conta do portador está bloqueada. Solicite aoportador que entre em contato com seu banco emissor.', False),
    'BV': ('Transação não autorizada. Cartão vencido.', 'Transação não autorizada. Cartão vencido.', False),
    'CF': ('Transação não autorizada. Falha na validação dos dados.', 'Transação não autorizada. Falha na validação dos dados. Solicite ao portador que entre em contato com o banco emissor.', False),
    'EE': ('Transação não permitida. Valor da parcela inferior ao mínimo permitido.', 'Transação não permitida. Valor da parcela inferior ao mínimo permitido. Não é permitido parcelas inferiores a R$ 5,00. Necessário rever calculo para parcelas.', False),
    'FA': ('Transação não autorizada.', 'Transação não autorizada AMEX.', False),
    'FC': ('Transação não autorizada. Ligue emissor', 'Transação não autorizada. Oriente o portador a entrar em contato com o banco emissor.', False),
    'GA': ('Transação não autorizada.', 'Referida pelo Cielo. Oriente o portador a aguardar alguns instantes e tentar novamente', True),
    'GD': ('Transação não permitida.', 'Transação não é possível ser processada no estabelecimento.Entre em contato com a administradora do cartão para obter mais detalhes.', True),
    'KA': ('Transação não permitida. Falha na validação dos dados.', 'Transação não permitida. Houve uma falha na validação dos dados. Solicite ao portador que reveja os dados e tente novamente.', True),
    'KE': ('Transação não autorizada. Falha na validação dos dados.', 'Transação não autorizada. Falha na validação dos dados.', False),
    'N7': ('Transação não autorizada. Código de segurança inválido.', 'Transação não autorizada. Código de segurança inválido. Oriente o portador corrigir os dados e tentar novamente.', True),
    'TEF': ('Solicitar Assinatura.', 'Operador deve pressionar Enter.', False),
    'DAI': ('Data abertura invalida.', 'PDV com fechamento parcial. Fazer o procedimento de fechamento para logo dar entrada ao operador.', True),
}